version: '3.9'
services:

  journalnode-1:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java8
    container_name: journalnode-1
    hostname: journalnode-1
    environment:
      - HADOOP_TYPE=journalnode
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net

  journalnode-2:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java8
    container_name: journalnode-2
    hostname: journalnode-2
    environment:
      - HADOOP_TYPE=journalnode
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    depends_on: 
      - journalnode-1

  journalnode-3:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java8
    container_name: journalnode-3
    hostname: journalnode-3
    environment:
      - HADOOP_TYPE=journalnode
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    depends_on: 
      - journalnode-2

  zoo-1:
    image: ezeparziale/zookeeper-docker:1.1.0
    container_name: zoo-1
    hostname: zoo-1
    environment:
      - HADOOP_TYPE=zookeeper
      - myid=1
    env_file: 
      - ./zoo.env
    networks: 
      - hadoop-net
    depends_on: 
      - journalnode-3

  zoo-2:
    image: ezeparziale/zookeeper-docker:1.1.0
    container_name: zoo-2
    hostname: zoo-2
    environment:
      - HADOOP_TYPE=zookeeper
      - myid=2
    env_file: 
      - ./zoo.env
    networks: 
      - hadoop-net  
    depends_on: 
      - zoo-1

  zoo-3:
    image: ezeparziale/zookeeper-docker:1.1.0
    container_name: zoo-3
    hostname: zoo-3
    environment:
      - HADOOP_TYPE=zookeeper
      - myid=3
    env_file: 
      - ./zoo.env
    networks: 
      - hadoop-net  
    depends_on: 
      - zoo-2

  hadoop-master-1:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java8
    container_name: hadoop-master-1
    ports:
      - 9870:9870
      - 9000:9000
    hostname: hadoop-master-1
    environment:
      - HADOOP_TYPE=nn1
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    depends_on: 
      - zoo-3

  hadoop-master-2:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java8
    container_name: hadoop-master-2
    ports:
      - 9872:9870
      - 9002:9000
    hostname: hadoop-master-2
    environment:
      - HADOOP_TYPE=nn2
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    depends_on: 
      - hadoop-master-1

  hadoop-master-3:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java8
    container_name: hadoop-master-3
    ports:
      - 9873:9870
      - 9003:9000
    hostname: hadoop-master-3
    environment:
      - HADOOP_TYPE=nn3
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    depends_on: 
      - hadoop-master-2

  hadoop-worker-1:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java8
    container_name: hadoop-worker-1
    ports:
      - 9864:9864
    hostname: hadoop-worker-1
    environment:
      - HADOOP_TYPE=datanode
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    volumes:
      - hadoop-volume-worker-1:/hadoop-data

  hadoop-worker-2:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java8
    container_name: hadoop-worker-2
    ports:
      - 9865:9864
    hostname: hadoop-worker-2
    environment:
      - HADOOP_TYPE=datanode
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    volumes:
      - hadoop-volume-worker-2:/hadoop-data

networks:
  hadoop-net:
    name: hadoop-net
    
volumes: 
  hadoop-volume-worker-1:
  hadoop-volume-worker-2: