version: '3.9'
services:

  hadoop-master:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java11
    container_name: hadoop-master
    ports:
      - 9870:9870
      - 9000:9000
    hostname: hadoop-master
    environment:
      - HADOOP_TYPE=namenode
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    volumes:
      - hadoop-volume-master:/hadoop-data

  hadoop-worker-1:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java11
    container_name: hadoop-worker-1
    ports:
      - 9864:9864
    hostname: hadoop-worker-1
    environment:
      - HADOOP_TYPE=datanode
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    volumes:
      - hadoop-volume-worker-1:/hadoop-data

  hadoop-worker-2:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java11
    container_name: hadoop-worker-2
    ports:
      - 9865:9864
    hostname: hadoop-worker-2
    environment:
      - HADOOP_TYPE=datanode
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    volumes:
      - hadoop-volume-worker-2:/hadoop-data

  hadoop-secondarynamenode-1:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java11
    container_name: hadoop-secondarynamenode-1
    ports:
      - 9868:9868
    hostname: hadoop-secondarynamenode-1
    environment:
      - HADOOP_TYPE=secondarynamenode
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    volumes:
      - hadoop-volume-secondarynamenode-1:/hadoop-data

  hadoop-nodemanager-1:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java11
    container_name: hadoop-nodemanager-1
    ports: 
      - 8042:8042
    hostname: hadoop-nodemanager-1
    environment:
      - HADOOP_TYPE=nodemanager
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    volumes:
      - hadoop-volume-nodemanager-1:/hadoop-data

  hadoop-nodemanager-2:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java11
    container_name: hadoop-nodemanager-2
    ports: 
      - 8043:8042
    hostname: hadoop-nodemanager-2
    environment:
      - HADOOP_TYPE=nodemanager
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    volumes:
      - hadoop-volume-nodemanager-2:/hadoop-data

  hadoop-resourcemanager-1:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java11
    container_name: hadoop-resourcemanager-1
    ports:
      - 8088:8088
    hostname: hadoop-resourcemanager-1
    environment:
      - HADOOP_TYPE=resourcemanager
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    volumes:
      - hadoop-volume-resourcemanager-1:/hadoop-data

  hadoop-historyserver-1:
    image: ezeparziale/hadoop-docker:1.1.0-hadoop3.3.4-ubuntu-java11
    container_name: hadoop-historyserver-1
    ports:
      - 19888:19888
    hostname: hadoop-historyserver-1
    environment:
      - HADOOP_TYPE=historyserver
    env_file: 
      - ./hadoop.env
    networks: 
      - hadoop-net
    volumes:
      - hadoop-volume-historyserver-1:/hadoop-data

networks:
  hadoop-net:
    name: hadoop-net
    
volumes: 
  hadoop-volume-master:
  hadoop-volume-worker-1:
  hadoop-volume-worker-2:
  hadoop-volume-secondarynamenode-1:
  hadoop-volume-resourcemanager-1:
  hadoop-volume-nodemanager-1:
  hadoop-volume-nodemanager-2:
  hadoop-volume-historyserver-1: